name = "mr-nook"
main = "src/worker.js"
compatibility_date = "2025-09-01"
workers_dev = true

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "mr-nook"
database_id = "00000000-0000-0000-0000-000000000000"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "mr-nook"

[observability]
enabled = true
